import { InMemoryDbService } from 'angular-in-memory-web-api';
 
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const bussesList = [
      {
          "travelName": "Orange Travels",
          "travelID": 101,
          "driverID":1001,
          "busID" : 10001,        
          "busType":"A/C Sleeper(2+1)",
          "busSeats":50,
          "movie":true,
          "chargingPoints":true,
          "blanket":false,
          "waterBottle":false,
          "wifi":false,
          "journeyID" : 201,
          "source":"Hyderabad",
          "destination":"Bhimavaram",
          "bordingTime":"23:00",
          "dropingTime":"09:00",
          "travelDate":"31/08/2018",
          "fare":800
      },
      {
          "travelName": "Morning Star Travels",
          "travelID": 102,
          "driverID":1006,
          "busID" : 10002,        
          "busType":"A/C Seater(2+1)",
          "busSeats":50,
          "movie":false,
          "chargingPoints":true,
          "blanket":true,
          "waterBottle":true,
          "wifi":false,
          "journeyID" : 202,
          "source":"Hyderabad",
          "destination":"Bhimavaram",
          "bordingTime":"20:00",
          "dropingTime":"23:30",
          "travelDate":"31/08/2018",
          "fare":200
      },
      {
          "travelName": "Morning Star Travels",
          "travelID": 102,
          "driverID":1006,
          "busID" : 10003,        
          "busType":"A/C Sleeper(2+1)",
          "busSeats":50,
          "movie":true,
          "chargingPoints":true,
          "blanket":true,
          "waterBottle":true,
          "wifi":true,
          "journeyID" : 203,
          "source":"Hyderabad",
          "destination":"Bhimavaram",
          "bordingTime":"06:00",
          "dropingTime":"12:30",
          "travelDate":"24/08/2018",
          "fare":600
      },
      {
          "travelName": "Mozo Travels",
          "travelID": 104,
          "driverID":1005,
          "busID" : 10004,        
          "busType":"A/C Sleeper(2+1)",
          "busSeats":50,
          "movie":true,
          "chargingPoints":true,
          "blanket":true,
          "waterBottle":true,
          "wifi":true,
          "journeyID" : 204,
          "source":"Vizag",
          "destination":"Vijayawada",
          "bordingTime":"05:00",
          "dropingTime":"11:30",
          "travelDate":"24/08/2018",
          "fare":600
      },
      {
          "travelName": "Kaveri Travels",
          "travelID": 105,
          "driverID":1005,
          "busID" : 10005,        
          "busType":"Non A/C Sleeper (2+1)",
          "busSeats":50,
          "movie":true,
          "chargingPoints":true,
          "blanket":false,
          "waterBottle":true,
          "wifi":false,
          "journeyID" : 208,
          "source":"Vizag",
          "destination":"Hyderabad",
          "bordingTime":"06:00",
          "dropingTime":"22:30",
          "travelDate":"13/09/2018",
          "fare":900
      },
      {
          "travelName": "Svkdt Travels",
          "travelID": 103,
          "driverID":1007,
          "busID" : 10006,        
          "busType":"A/C Sleeper(2+1)",
          "busSeats":50,
          "movie":true,
          "chargingPoints":true,
          "blanket":true,
          "waterBottle":true,
          "wifi":true,
          "journeyID" : 205,
          "source":"Rajamundry",
          "destination":"Vijayawada",
          "bordingTime":"08:00",
          "dropingTime":"11:30",
          "travelDate":"12/12/2018",
          "fare":300
          
      },
      {
          "travelName": "Jagan Travels",
          "travelID" : 106,
          "driverID": 1008,
          "busID" : 10007,        
          "busType":"A/C Sleeper(2+1)",
          "busSeats":50,
          "movie":true,
          "chargingPoints":true,
          "blanket":true,
          "waterBottle":true,
          "wifi":true,
          "journeyID" : 206,
          "source":"Vijayanagaram",
          "destination":"Vijayawada",
          "bordingTime":"08:00",
          "dropingTime":"13:30",
          "travelDate":"22/12/2018",
          "fare":700
         
      },
      {
          "travelName": "Jagan Travels",
          "travelID" : 106,
          "driverID": 1008,
          "busID" : 10007,        
          "busType":"A/C Sleeper(2+1)",
          "busSeats":50,
          "movie":true,
          "chargingPoints":true,
          "blanket":true,
          "waterBottle":true,
          "wifi":true,
          "journeyID" : 206,
          "source":"Vijayanagaram",
          "destination":"Vijayawada",
          "bordingTime":"08:00",
          "dropingTime":"13:30",
          "travelDate":"22/12/2018",
          "fare":700
         
      },
      {
          "travelName": "Mozo Travels",
          "travelID" : 104,
          "driverID": 1004,
          "busID" : 10002,
          "busType":"Non A/C Seater(2+1)",
          "busSeats":50,
          "movie":true,
          "chargingPoints":true,
          "blanket":false,
          "waterBottle":true,
          "wifi":false,
          "journeyID" : 208,
          "source":"Vizag",
          "destination":"Hyderabad",
          "bordingTime":"06:00",
          "dropingTime":"22:30",
          "travelDate":"13/09/2018",
          "fare":900
  
      },
      {
          "travelName": "Orange Travels",
          "travelID" : 101,
          "driverID": 1003,
          "busID" : 10006,
          "busType":"Non A/C Seater(2+1)",
          "busSeats":50,
          "movie":true,
          "chargingPoints":true,
          "blanket":false,
          "waterBottle":true,
          "wifi":false,
          "journeyID" : 208,
          "source":"Vizag",
          "destination":"Chennai",
          "bordingTime":"06:00",
          "dropingTime":"23:30",
          "travelDate":"23/09/2018",
          "fare":1000
  
      },
      {
          "travelName": "Svkdt Travels",
          "travelID" : 103,
          "driverID": 1003,
          "busID" : 10007,
          "busType":"A/C Seater(2+1)",
          "busSeats":50,
          "movie":true,
          "chargingPoints":true,
          "blanket":false,
          "waterBottle":true,
          "wifi":false,
          "journeyID" : 208,
          "source":"Vizag",
          "destination":"Banglore",
          "bordingTime":"04:00",
          "dropingTime":"23:30",
          "travelDate":"15/12/2018",
          "fare":1200
  
      },
      {
          "travelName": "Kaveri Travels",
          "travelID" : 105,
          "driverID": 1002,
          "busID" : 10007,
          "busType":"A/C Seater(2+1)",
          "busSeats":50,
          "movie":true,
          "chargingPoints":true,
          "blanket":false,
          "waterBottle":true,
          "wifi":false,
          "journeyID" : 208,
          "source":"Banglore",
          "destination":"Hyderabad",
          "bordingTime":"04:00",
          "dropingTime":"23:30",
          "travelDate":"20/11/2018",
          "fare":1200
  
      } 
  ];
    return {bussesList};
  }
}